# Generated by Django 3.2.9 on 2021-11-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_first_name', models.CharField(max_length=60)),
                ('author_last_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('available', models.BooleanField()),
                ('publication_year', models.DateTimeField()),
                ('publication_city', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
            ],
        ),
    ]
