# Generated by Django 3.2.9 on 2021-12-04 11:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('books', '0003_alter_book_publication_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True)),
                ('birth_year', models.IntegerField(blank=True)),
                ('birth_city', models.CharField(blank=True, max_length=255)),
                ('death_year', models.IntegerField(blank=True)),
                ('death_city', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, main.models.CheckAgeMixin),
        ),
        migrations.RenameField(
            model_name='book',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='modified_at',
            new_name='modified',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_first_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_last_name',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.Author'),
        ),
    ]
