# Generated by Django 3.2.9 on 2022-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='death_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
