# Generated by Django 3.2.9 on 2021-12-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='example_files',
            new_name='example_file',
        ),
    ]
