# Generated by Django 3.2.9 on 2021-12-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_example_files_post_example_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='example_file',
        ),
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.ImageField(null=True, upload_to='posts/2021/12/09/'),
        ),
    ]
