# Generated by Django 3.2.9 on 2022-01-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211209_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/'),
        ),
    ]
