# Generated by Django 3.2.9 on 2022-01-28 18:31

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/'),
        ),
    ]
