# Generated by Django 3.2.9 on 2021-12-02 20:15

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('is_alive', models.BooleanField(default=True)),
                ('birth_date', models.DateTimeField()),
                ('birth_city', models.CharField(max_length=255)),
                ('death_date', models.DateTimeField()),
                ('death_city', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, main.models.CheckAgeMixin),
        ),
    ]
