# Generated by Django 3.2.9 on 2022-02-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20220130_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'hide'), (2, 'published'), (3, 'new')], default=3),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'hide'), (2, 'published'), (3, 'new')], default=3),
        ),
    ]
