# Generated by Django 3.2.9 on 2022-02-25 16:59

from django.db import migrations, models
import galleries.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20220213_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=galleries.models.upload_to),
        ),
    ]
